name       : qt5-webengine
version    : 5.15.10
release    : 48
source     :
    - git|https://code.qt.io/qt/qtwebengine.git : v5.15.10-lts
homepage   : https://www.qt.io
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : QtWebEngine integrates chromium's fast moving web capabilities into Qt
description: |
    QtWebEngine integrates chromium's fast moving web capabilities into Qt
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(harfbuzz)
    - pkgconfig(icu-io)
    - pkgconfig(jsoncpp)
    - pkgconfig(lcms2)
    - pkgconfig(libavcodec)
    - pkgconfig(libcap)
    - pkgconfig(libdrm)
    - pkgconfig(libevent)
    - pkgconfig(libjpeg)
    - pkgconfig(libpci)
    - pkgconfig(libpng)
    - pkgconfig(libpulse)
    - pkgconfig(libsrtp2)
    - pkgconfig(libwebp)
    - pkgconfig(libxslt)
    - pkgconfig(minizip)
    - pkgconfig(nss)
    - pkgconfig(openssl)
    - pkgconfig(opus)
    - pkgconfig(protobuf)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Positioning)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(Qt5WebChannel)
    - pkgconfig(vpx)
    - pkgconfig(xcb)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xdamage)
    - pkgconfig(xext)
    - pkgconfig(xkbcommon)
    - pkgconfig(xkbfile)
    - pkgconfig(xrandr)
    - pkgconfig(xtst)
    - pkgconfig(xscrnsaver)
    - gperf
    - ninja
    - nodejs
    - re2-devel
    - snappy-devel
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
environment: |
    unset LDFLAGS
setup      : |
    %patch -p1 -i $pkgfiles/gcc-12.patch
    %patch -p1 -i $pkgfiles/fix-clang-14.patch
    sed -i 's|MODULE_VERSION = 5.15.10|MODULE_VERSION = 5.15.5|g' .qmake.conf
    sed -i -e 's|use_jumbo_build=true|use_jumbo_build=false|' src/buildtools/config/common.pri
    %qmake QMAKE_C=clang QMAKE_CXX=clang++ CONFIG+=use_lld_linker \
        qtwebengine.pro -- \
        -system-webengine-ffmpeg \
        -webengine-proprietary-codecs \
        -webengine-spellchecker
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
