name       : qt5-webengine
version    : 5.6.2
release    : 6
source     :
    - git|https://github.com/qt/qtwebengine : v5.6.2
license    :
    - GPL-2.0
    - GPL-3.0
    - LGPL-3.0
component  : desktop.qt
summary    : QtWebEngine integrates chromium's fast moving web capabilities into Qt
description: |
    QtWebEngine integrates chromium's fast moving web capabilities into Qt
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(harfbuzz)
    - pkgconfig(gl)
    - pkgconfig(jsoncpp)
    - pkgconfig(libavcodec)
    - pkgconfig(libdrm)
    - pkgconfig(libevent)
    - pkgconfig(libpci)
    - pkgconfig(libpng)
    - pkgconfig(libpulse)
    - pkgconfig(libsrtp2)
    - pkgconfig(libwebp)
    - pkgconfig(libxslt)
    - pkgconfig(nss)
    - pkgconfig(openssl)
    - pkgconfig(opus)
    - pkgconfig(protobuf)
    - pkgconfig(Qt5Positioning)
    - pkgconfig(Qt5WebChannel)
    - pkgconfig(vpx)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xrandr)
    - pkgconfig(xtst)
    - pkgconfig(xscrnsaver)
    - gperf
    - libcap2-devel
    - libjpeg-turbo-devel
    - ninja
    - re2c
    - snappy-devel
setup      : |
    unset LDFLAGS
    qmake WEBENGINE_CONFIG+="use_system_icu use_system_ffmpeg use_proprietary_codecs" \
          CONFIG+=release \
          WEBKIT_CONFIG-=build_tests
build      : |
    unset LDFLAGS
    %make
install    : |
    unset LDFLAGS
    %make_install INSTALL_ROOT=$installdir
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
