name       : qt5-webengine
version    : 5.10.1
release    : 19
source     :
    - https://download.qt.io/official_releases/qt/5.10/5.10.1/submodules/qtwebengine-everywhere-src-5.10.1.tar.xz : 12644f8d2ba8354a2a533d5a7f3f5139c6ff168c2f51aa3e21b701db6dbc01de
license    :
    - GPL-2.0
    - GPL-3.0
    - LGPL-3.0
component  : desktop.qt
summary    : QtWebEngine integrates chromium's fast moving web capabilities into Qt
description: |
    QtWebEngine integrates chromium's fast moving web capabilities into Qt
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(harfbuzz)
    - pkgconfig(icu-io)
    - pkgconfig(jsoncpp)
    - pkgconfig(lcms2)
    - pkgconfig(libavcodec)
    - pkgconfig(libcap)
    - pkgconfig(libdrm)
    - pkgconfig(libevent)
    - pkgconfig(libjpeg)
    - pkgconfig(libpci)
    - pkgconfig(libpng)
    - pkgconfig(libpulse)
    - pkgconfig(libsrtp2)
    - pkgconfig(libwebp)
    - pkgconfig(libxslt)
    - pkgconfig(minizip)
    - pkgconfig(nss)
    - pkgconfig(openssl)
    - pkgconfig(opus)
    - pkgconfig(protobuf)
    - pkgconfig(Qt5Positioning)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5WebChannel)
    - pkgconfig(vpx)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xrandr)
    - pkgconfig(xtst)
    - pkgconfig(xscrnsaver)
    - gperf
    - ninja
    - re2-devel
    - snappy-devel
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
setup      : |
    %patch -p1 < $pkgfiles/security/qtwebengine-everywhere-src-5.10.1-security-5.9.5.patch
    %patch -p1 < $pkgfiles/security/cve-2018-6033.patch

    unset LDFLAGS
    export CXXFLAGS="${CXXFLAGS/-fexceptions/} -fno-exceptions"
    qmake -- \
          -system-webengine-ffmpeg \
          -webengine-proprietary-codecs \
          -webengine-spellchecker
build      : |
    unset LDFLAGS
    export CXXFLAGS="${CXXFLAGS/-fexceptions/} -fno-exceptions"
    %make
install    : |
    unset LDFLAGS
    %make_install INSTALL_ROOT=$installdir

    # Come up with less of a hack - Only require 5.10.0
    sed -i -e "s|${version} \${_Qt5WebEngine|5.10.0 \${_Qt5WebEngine|" $installdir/%libdir%/cmake/Qt5WebEngine*/Qt5WebEngine*Config.cmake
