name       : qt5-webengine
version    : 5.13.2
release    : 32
source     :
    - https://download.qt.io/official_releases/qt/5.13/5.13.2/submodules/qtwebengine-everywhere-src-5.13.2.tar.xz : adcf56b5de6f34744bba2307b696fc75611884f4270e87dfa760d6e99dd711bb
homepage   : https://www.qt.io
license    :
    - GPL-2.0
    - GPL-3.0
    - LGPL-3.0
component  : desktop.qt
summary    : QtWebEngine integrates chromium's fast moving web capabilities into Qt
description: |
    QtWebEngine integrates chromium's fast moving web capabilities into Qt
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(harfbuzz)
    - pkgconfig(icu-io)
    - pkgconfig(jsoncpp)
    - pkgconfig(lcms2)
    - pkgconfig(libavcodec)
    - pkgconfig(libcap)
    - pkgconfig(libdrm)
    - pkgconfig(libevent)
    - pkgconfig(libjpeg)
    - pkgconfig(libpci)
    - pkgconfig(libpng)
    - pkgconfig(libpulse)
    - pkgconfig(libsrtp2)
    - pkgconfig(libwebp)
    - pkgconfig(libxslt)
    - pkgconfig(minizip)
    - pkgconfig(nss)
    - pkgconfig(openssl)
    - pkgconfig(opus)
    - pkgconfig(protobuf)
    - pkgconfig(Qt5Positioning)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5WebChannel)
    - pkgconfig(vpx)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xrandr)
    - pkgconfig(xtst)
    - pkgconfig(xscrnsaver)
    - gperf
    - ninja
    - re2-devel
    - snappy-devel
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
environment: |
    unset LDFLAGS
setup      : |
    %qmake -- \
            -system-webengine-ffmpeg \
            -webengine-proprietary-codecs \
            -webengine-spellchecker
build      : |
    %make
install    : |-
    %make_install INSTALL_ROOT=$installdir
