name       : qt5-webengine
version    : 5.15.15
release    : 55
source     :
    - git|https://code.qt.io/qt/qtwebengine.git : v5.15.15-lts
homepage   : https://www.qt.io
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : QtWebEngine integrates chromium's fast moving web capabilities into Qt
description: |
    QtWebEngine integrates chromium's fast moving web capabilities into Qt
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(harfbuzz)
    - pkgconfig(icu-io)
    - pkgconfig(jsoncpp)
    - pkgconfig(lcms2)
    - pkgconfig(libavcodec)
    - pkgconfig(libcap)
    - pkgconfig(libdrm)
    - pkgconfig(libevent)
    - pkgconfig(libjpeg)
    - pkgconfig(libpci)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libpng)
    - pkgconfig(libpulse)
    - pkgconfig(libsrtp2)
    - pkgconfig(libwebp)
    - pkgconfig(libxslt)
    - pkgconfig(minizip)
    - pkgconfig(nss)
    - pkgconfig(openssl)
    - pkgconfig(opus)
    - pkgconfig(protobuf)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Positioning)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(Qt5WebChannel)
    - pkgconfig(vpx)
    - pkgconfig(xcb)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xdamage)
    - pkgconfig(xext)
    - pkgconfig(xkbcommon)
    - pkgconfig(xkbfile)
    - pkgconfig(xrandr)
    - pkgconfig(xtst)
    - pkgconfig(xscrnsaver)
    - gperf
    - ninja
    - nodejs
    - re2-devel
    - snappy-devel
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
environment: |
    unset LDFLAGS
setup      : |
    git config --global user.email "solus@getsol.us"
    git config --global user.name "Solus"

    # Multiple CVEs
    git cherry-pick 00c524f3a8c164aed4eaee203f151fb18d5c4e90

    %patch -p1 -i $pkgfiles/gcc-12.patch
    %patch -p1 -i $pkgfiles/fix-clang-14.patch
    %patch -p1 -d src/3rdparty -i $pkgfiles/qt5-webengine-pipewire-0.3.patch
    sed -i -e 's|use_jumbo_build=true|use_jumbo_build=false|' src/buildtools/config/common.pri
    %qmake QMAKE_C=clang QMAKE_CXX=clang++ CONFIG+=use_lld_linker \
        qtwebengine.pro -- \
        -system-webengine-ffmpeg \
        -webengine-proprietary-codecs \
        -webengine-spellchecker \
        -webengine-webrtc-pipewire
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
