name       : qt5-webengine
version    : 5.9.2
release    : 17
source     :
    - https://download.qt.io/official_releases/qt/5.9/5.9.2/submodules/qtwebengine-opensource-src-5.9.2.tar.xz : cab069e4589f806640bebe4077c70e5cd5ffeb146c6e8caca6c4454fc0c4a108
license    :
    - GPL-2.0
    - GPL-3.0
    - LGPL-3.0
component  : desktop.qt
summary    : QtWebEngine integrates chromium's fast moving web capabilities into Qt
description: |
    QtWebEngine integrates chromium's fast moving web capabilities into Qt
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(harfbuzz)
    - pkgconfig(icu-io)
    - pkgconfig(jsoncpp)
    - pkgconfig(libavcodec)
    - pkgconfig(libcap)
    - pkgconfig(libdrm)
    - pkgconfig(libevent)
    - pkgconfig(libjpeg)
    - pkgconfig(libpci)
    - pkgconfig(libpng)
    - pkgconfig(libpulse)
    - pkgconfig(libsrtp2)
    - pkgconfig(libwebp)
    - pkgconfig(libxslt)
    - pkgconfig(minizip)
    - pkgconfig(nss)
    - pkgconfig(openssl)
    - pkgconfig(opus)
    - pkgconfig(protobuf)
    - pkgconfig(Qt5Positioning)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5WebChannel)
    - pkgconfig(vpx)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xrandr)
    - pkgconfig(xtst)
    - pkgconfig(xscrnsaver)
    - gperf
    - ninja
    - re2c
    - snappy-devel
setup      : |
    unset LDFLAGS
    export CXXFLAGS="${CXXFLAGS/-fexceptions/} -fno-exceptions"
    qmake WEBENGINE_CONFIG+="use_system_icu use_system_ffmpeg use_proprietary_codecs" \
          CONFIG+=release \
          WEBKIT_CONFIG-=build_tests
build      : |
    unset LDFLAGS
    export CXXFLAGS="${CXXFLAGS/-fexceptions/} -fno-exceptions"
    %make
install    : |
    unset LDFLAGS
    %make_install INSTALL_ROOT=$installdir
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
